### ISSUE TITLE
mainApp/views.py > search_result 페이지 추가 설명 요청

### ISSUE THREAD

**Issue by pcjs156** [pcjs156/Match_Tattoo#5]
**1. View**
https://github.com/pcjs156/Match_Tattoo/blob/6ddb1d1a8b7ff5ec35edc7b812ad6529e57dc537/mainApp/views.py#L62-L77
mainApp/views.py > search_result_view 페이지네이션쪽 로직이 잘 이해가 안 되는데, 혹시 설명해주실 수 있으신가요? 

1. 보여질 페이지 범위 지정(p_range)이라는게 section 하단부의 페이지네이션 번호를 얘기하는 게 맞나요? 페이지네이션 방법을 정해야 하는데, 디자인/프론트엔드 담당 하시는 분들이랑도 얘기해보고 tattooist_profile_view와 같이 페이지네이션을 구현할지, 아니면 주영찌가 구현한대로 할지 정해야 될 것 같네용..!
2. 와이어프레임을 확인해 보니까 search_result_view 페이지에 표시되는 게시물이 2개가 아닌 것 같은데 확인 부탁드립니다! 어떤 의도로 코드를 작성하신 건지 잘 모르겠어서 따로 수정은 안 했습니당 ㅎㅎ

**2. Template**
https://github.com/pcjs156/Match_Tattoo/blob/6ddb1d1a8b7ff5ec35edc7b812ad6529e57dc537/mainApp/templates/search_result.html#L54-L58
이 부분 로직이 잘 이해가 안 되는데, elif q 블록은 조건에 맞는 검색어가 없을 때 렌더링되고, else 블록은 아무런 검색어도 입력되지 않았을 때 렌더링 되지 않나요?
조건에 맞지 않는 매칭이 없는 검색어를 입력했을 때 elif q 블록이 아니라 else 블록이 실행되어서 질문 드립니당..

**Comment by anthologia** [comment]
1. 오... 유빈님이 구현한 코드가 더 세련되고 보기 편한 것 같아요!! Swit에서 정해서 유빈님 방식으로...

2, 3. 새벽에 구현했던 거라서 블록 블록으로 가져와서 일단 기능만 넣어두고 디테일한 부분은 나중에 수정해야지,,, 했는데 여러모로 요상한 부분이 많네요😓

**Comment by pcjs156** [comment]
1. 그럼 적절히 타협해서, 처음/왼쪽/페이지 넘버/오른쪽/끝으로 페이지네이션 구현하는 건 어떨까요?!
2. 3. 아직 미완성이었군요! 새벽 6시까지 코딩하는 당신 근성 무엇 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
나중에 그럼 천천히 고쳐주세용 ㅎㅎ 고생하셨습니다
